### ISSUE TITLE
Error retrieving programs scope

### ISSUE THREAD

**Issue by yassineaboukir** [serain/bbrecon#3]
Hi,

Thanks for the service you are building! I am running into an issue every single time I run call this call:

```python
for program in programs:
    domains = list(bb.domains(programs=[program.slug]))
    for domain in domains[:3]:
        print(domain.name)
```

The JSON output from the source is probably not properly formatted. See:

```
[...]
 kraken.realself.com
charon.realself.com
Traceback (most recent call last):
  File "bb.py", line 10, in <module>
    domains = list(bb.domains(programs=[program.slug]))
  File "/usr/local/lib/python3.8/dist-packages/bbrecon/manager.py", line 55, in domains
    for domain in paginate(
  File "/usr/local/lib/python3.8/dist-packages/bbrecon/utils.py", line 4, in paginate
    response = api_function(client=client, page=page, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bbrecon/api/domains.py", line 32, in get_domains
    raise ApiResponseError(code=response.status_code, detail=response.json())
  File "/usr/local/lib/python3.8/dist-packages/httpx/_models.py", line 854, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by serain** [comment]
Hey @yassineaboukir ,

I can't seem to reproduce this on my end.

**Comment by yassineaboukir** [comment]
Hi,

Thanks for the follow-up! It looks like it's working just fine now.

Closing now, cheers!
